	LIST P=16F887
	;RADIX HEX
; CONFIG1
; __config 0xFFF2
 __CONFIG _CONFIG1, _FOSC_HS & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _CP_OFF & _CPD_OFF & _BOREN_ON & _IESO_ON & _FCMEN_ON & _LVP_ON
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF
#include "p16f887.inc"

W_TEMP EQU 0x20
STATUS_TEMP EQU 0x21
COLUMN EQU 0x22 ; VARIABLE DECIMAL DE LA COLUMNA
ROW EQU 0x23 ; VARIABLE DECIMAL DE LA FILA
COL_EN EQU 0x24 ; VARIABLE DONDE SE GUARDA LA COLUMNA ACTIVADA
COL_EN_T EQU 0x25 ; VARIABLE DONDE SE GUARDA LA COLUMNA ACTIVADA TEMPORAL
N_COL EQU 3 ; CANTIDAD MAXIMA DE COLUMNAS
N_ROW EQU 4 ; CANTIDAD MAXIMA DE FILAS
FLAGS EQU 0x26 ; BIT FLAG QUE ENTRO EN INTERRUPT
INTRB EQU 0
FLANCO EQU 1
DISPLAY0 EQU 0x27
DISPLAY1 EQU 0x28
DISPLAY2 EQU 0x29
DISPLAY3 EQU 0x2A
CONT_D	 EQU 0x2B 
AUX_DECO EQU 0x2C
DISPCOUNT EQU 0x2D
AUX_REG EQU 0x2E 
   
   ORG 0x00  
   GOTO INIT

   ORG 0x04
   GOTO INTERRUPT_SERVE

   ORG 0x05
INIT 
   ;PUERTOS
   BANKSEL TRISC
   MOVLW 0x0F
   MOVWF TRISB ; TECLADO
   CLRF TRISD ; SALIDA DE LOS DISPLAYS
   CLRF TRISA
   BCF OPTION_REG, 7 ; ACTIVO PULL UP EN PUERTO B
   MOVLW 0x0E
   MOVWF WPUB ; ACTIVO PULL UP EN PINES DE ENTRADA
   BANKSEL ANSELH
   CLRF ANSELH
   CLRF ANSEL
   BANKSEL PORTC
   CLRF PORTB
   CLRF PORTC
   CLRF PORTD
   CLRF PORTA
   
   ;REGISTROS
   CLRF FLAGS
   MOVLW DISPLAY0
   MOVWF FSR; INICIALIZAMOS FSR EN EL PRIMER REGISTRO DE LOS VALORES DE LOS DISPLAYS
   CLRF CONT_D
   DECF CONT_D,F ; INICIALIZAMOS EN .255
   CLRF DISPCOUNT
   
   ;INTERRUPCIONES
   BANKSEL IOCB
   MOVLW 0x0E
   MOVWF IOCB ; ACTIVO INTERRUPCIONES EN LOS PINES PORTB<3:1> SON ENTRADA
   BCF INTCON, RBIF
   BSF INTCON, RBIE ; ACTIVO INTERRUPCIONES POR PUERTO B
   MOVLW B'00000100' ; PRESCALER A 32
   MOVWF OPTION_REG
   BSF INTCON, GIE ; ACTIVO INTERRUPCIONES GLOBALES
   
   
   GOTO PROGRAMA
  
PROGRAMA
   CALL CHECK_TECLADO
   BTFSS FLAGS, INTRB
   GOTO PROGRAMA
   BCF FLAGS, INTRB
   CALL ACT_DISPLAYS
   

CHECK_TECLADO
   BTFSS FLAGS, INTRB
   RETURN
   MOVF PORTB, W
   ANDLW 0x0F
   MOVWF COL_EN
   MOVWF COL_EN_T
   CLRF COLUMN 
   CLRF ROW
   CALL COL_DEC
   BCF STATUS, C
   MOVF COLUMN, W
   ADDWF ROW, W
   ADDWF ROW, W
   ADDWF ROW, W
   MOVWF PORTC
   ;BCF FLAGS, INTRB
   RETURN
   
COL_DEC
   RRF COL_EN_T, F
   BTFSS STATUS, C
   GOTO ROW_DEC
   INCF COLUMN, F
   MOVLW N_COL
   SUBWF COLUMN, W
   BTFSS STATUS, Z
   GOTO COL_DEC
   CLRF COLUMN
   GOTO FINEXP
ROW_DEC
   MOVF ROW, W
   CALL EN_ROW
   MOVWF PORTB
   MOVF PORTB, W
   ANDLW 0x0F
   SUBWF COL_EN, W
   BTFSC STATUS, Z
   GOTO FINEXP
   INCF ROW, F
   MOVLW N_ROW
   SUBWF ROW, W
   BTFSS STATUS, Z
   GOTO ROW_DEC
   CLRF ROW
   GOTO FINEXP

INTERRUPT_SERVE
   MOVWF W_TEMP
   SWAPF STATUS,W
   MOVWF STATUS_TEMP
   BTFSC INTCON, T0IF
   GOTO TMR0_INT
   BTFSS INTCON, RBIF
   GOTO ENDINT
   CALL CHECKBITS
   BTFSC FLAGS, FLANCO
   GOTO ENDINT
   BSF FLAGS, INTRB
   MOVF PORTB, W
   BCF INTCON, 0
   BSF PORTD, 0
   ;GOTO ENDINT
   
TMR0_INT
   BCF INTCON, T0IF
   MOVLW .100
   MOVWF TMR0
   BTFSC CONT_D, 7
   GOTO CLR_PORTA
   MOVF DISPCOUNT,W
   CALL TABLA_MUX
   MOVWF PORTA
   MOVF DISPCOUNT,W
   CALL TABLA_REG
   MOVWF AUX_REG
   MOVF AUX_REG,W
   CALL TABLA_SEGM
   MOVWF PORTD
   INCF DISPCOUNT,F
   MOVF DISPCOUNT,W
   SUBWF CONT_D,W
   BTFSC STATUS, C
   GOTO ENDINT
   CLRF DISPCOUNT
   GOTO ENDINT
   
   
   
CLR_PORTA
   CLRF PORTA
   CLRF DISPCOUNT
   GOTO ENDINT
   
ENDINT
   
   SWAPF W_TEMP,F
   SWAPF W_TEMP,W
   SWAPF STATUS_TEMP, W
   MOVWF STATUS
   RETFIE
   
FINEXP
   CLRF PORTB
   BCF FLAGS, INTRB
   RETURN
   
EN_ROW
   ADDWF PCL, F
   RETLW 0xE0; COL0
   RETLW 0xD0; COL1                
   RETLW 0xB0; COL2
   RETLW 0x70; COL3
   
CHECKBITS
   BSF FLAGS, FLANCO ; BIT DE BANDERA DE CAMBIO DE FLANCO
   BTFSS PORTB, 0
   BCF FLAGS, FLANCO
   BTFSS PORTB, 1
   BCF FLAGS, FLANCO
   BTFSS PORTB, 2
   BCF FLAGS, FLANCO
   BTFSS PORTB, 3
   BCF FLAGS, FLANCO
   RETURN
   
ACT_DISPLAYS
   CALL TABLA_DECO
   MOVWF AUX_DECO
   SUBLW .9
   BTFSS STATUS,C
   GOTO ACCION_DECO
   GOTO NUMERO_DECO
   
   
NUMERO_DECO
   MOVF CONT_D,W
   SUBLW .3
   BTFSC STATUS, Z
   RETURN
   MOVF AUX_DECO,W
   MOVWF INDF
   INCF	 CONT_D,F
   INCF FSR,F
   RETURN
   
ACCION_DECO
   BTFSS AUX_DECO, 0 ; .10=1010 Y .11=1011
   GOTO BORRAR_TECLA
   GOTO ACEPTAR_TECLA
   
   
ACEPTAR_TECLA
   
BORRAR_TECLA
   BTFSC CONT_D , 7
   RETURN
   DECF FSR,F
   DECF CONT_D
   RETURN
 
   

TABLA_MUX
   ADDWF PCL, F
   RETLW 0x01 ; DISPLAY 0
   RETLW 0x02 ; DISPLAY 1
   RETLW 0x04 ; DISPLAY 2
   RETLW 0x08 ; DISPLAY 3

TABLA_REG
   ADDWF PCL, F
   RETLW DISPLAY0
   RETLW DISPLAY1
   RETLW DISPLAY2
   RETLW DISPLAY3
   
TABLA_SEGM
    ADDWF PCL, F
    RETLW 0x3F; 0
    RETLW 0x06; 1
    RETLW 0x5B; 2
    RETLW 0x4F; 3
    RETLW 0x66; 4
    RETLW 0x6D; 5
    RETLW 0x7D; 6
    RETLW 0x07; 7
    RETLW 0x7F; 8
    RETLW 0x6F; 9   
   
TABLA_DECO
   ADDWF PCL, F
   RETLW .1
   RETLW .2
   RETLW .3
   RETLW .4
   RETLW .5
   RETLW .6 
   RETLW .7
   RETLW .8
   RETLW .9
   RETLW .10 ; TECLA BORRAR (ASTERISCO)
   RETLW .0
   RETLW .11 ; TECLA ACEPTAR (NUMERAL)
   
   END